[package]
name = "cryptoki"
version = "0.1.0"
authors = ["Contributors to the Parsec project"]
edition = '2018'
description = "Rust-native wrapper around the PKCS #11 API"
readme = "README.md"
keywords = ["pkcs11", "cryptoki", "hsm"]
categories = ["api-bindings", "external-ffi-bindings", "cryptography", "hardware-support"]
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/rust-cryptoki"
documentation = "https://docs.rs/crate/cryptoki"

[dependencies]
libloading = "0.6.1"
log = "0.4.11"
secrecy = "0.7.0"
psa-crypto = { git = "https://github.com/parallaxsecond/rust-psa-crypto", rev = "18dd4dda96d8b61d2e112b9e6ad83e90fe768d78", default-features = false, optional = true }
cryptoki-sys = { path = "../cryptoki-sys" }

[dev-dependencies]
num-traits = "0.2.11"
hex = "0.4.2"
serial_test = "0.4.0"
serial_test_derive = "0.4.0"

[features]
psa-crypto-conversions = ["psa-crypto"]
