name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Execute CI script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: Execute CI script
      #   run: ./ci.sh

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Install SoftHSM
        run: |
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq libsofthsm2 &&
          mkdir /tmp/tokens
          echo "directories.tokendir = /tmp/tokens" > /tmp/softhsm2.conf

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
          SOFTHSM2_CONF: /tmp/softhsm2.conf

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
